### ISSUE TITLE
Something wrong in 3dfuture2suncg.py

### ISSUE THREAD

**Issue by CharlieLei** [Shao-Kui/3DScenePlatform#23]
When running this code, I encounter this error.

```
Traceback (most recent call last):
  File "/home2/leicheng/3DScenePlatform/assets/3dfuture2suncg.py", line 411, in <module>
    main(args)
  File "/home2/leicheng/3DScenePlatform/assets/3dfuture2suncg.py", line 301, in main
    "coarseSemantic": meshes[child["ref"]]["type"] if child["ref"] in meshes else furnitures[child["ref"]]["category"],
KeyError: 'category'
```

And I found that all keys in dict furnitures are different from child["ref"].

**Comment by CharlieLei** [comment]
It may caused by the version of 3D-FRONT. According to the 3D-FRONT website, the latest dataset has been refined.

**Comment by Shao-Kui** [comment]
Hi @CharlieLei! Yes...the version of the dataset does matter. The version we are using is released before last year, July, and this script is designated for that version.

**Comment by k-bobin** [comment]
> Well, having the dataset can help me better understand the code. Would you please provide the dataset you used? Thank you so much!

I'm having exactly the same problem. How did you resolve the problem?
If you did, could you share it for me?
I'd really appreciate it

**Comment by Shao-Kui** [comment]
https://pan.baidu.com/s/1HqHcCOnHKK0VdNhiHmMDoA?pwd=fvya 
Extraction Code: fvya 

Hi, I have put all related files in this folder, including the dataset and extracted priors. 

Alternatively, you can go to this temporary website: http://166.111.71.59:11425/online/k-bobin
This website currently runs on our server, which is not stable. 

Please email me if you have more issues!

**Comment by k-bobin** [comment]
> https://pan.baidu.com/s/1HqHcCOnHKK0VdNhiHmMDoA?pwd=fvya Extraction Code: fvya
> 
> Hi, I have put all related files in this folder, including the dataset and extracted priors.
> 
> Alternatively, you can go to this temporary website: http://166.111.71.59:11425/online/k-bobin This website currently runs on our server, which is not stable.
> 
> Please email me if you have more issues!
Thank you for your reply
Your work seems very interesting and well-made.

But the thing is that I'm having a trouble downloading your files on Baidu.
Since two out of three files has such a big size, it would take pretty long time to complete downloading process. 
So could you send me the files to my email? my email is "bobinkim0@gmail.com"
I would really appreciate it!!!

**Comment by Shao-Kui** [comment]
Sorry for the inconvenience...It is also hard for us to email you the dataset. The files are too big, and our email system does not allow super-large files. We are looking for opportunities to upload the files in Google Drive (still, our personal account can not hold such a large file). 

Could you try our FTP server? 
166.111.71.59:11426
User Name: front
Password: 3d

If you refresh the website and it still does not work, our server may crash...Please email me if you have that issue. Another reason could be the campus network latency...
